name: fitness_app
description: Домашний фитнес-приложение с отслеживанием прогресса.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.60.0

flutter:
  uses-material-design: true
